# Docker Compose configuration for DCS-SRS (Digital Combat Simulator - Simple Radio Standalone) server
# This file defines how to run the SRS server in a Docker container
version: '3.8'

services:
  dcs-srs:
    # Container name - change this if you want a different name for your container
    container_name: dcs-srs

    # Docker image to use - only change if you need a different version
    image: jaycadi/dcs-srs-server:2.2.0.4-5

    deploy:
      # Number of container instances to run (1 = single server, 0 = disabled)
      replicas: 1  # Change to 0 or any number to scale
      restart_policy:
        # Restart container automatically if it crashes
        condition: any

    ports:
      # Port mapping: "host_port:container_port/protocol"
      # Change "5002" on the left to use a different port on your host machine
      - "5002:5002/udp"  # UDP port for voice communication
      - "5002:5002/tcp"  # TCP port for client connections and data
      - "8080:8080/tcp"  # REST API port (only expose if using REST API)

    # WORKING DIRECTORY & ENTRYPOINT
    working_dir: /opt/srs
    entrypoint: ["/opt/srs/entrypoint.sh"]

    volumes:
      # Mount host Presets directory to allow user-managed presets
      - "/docker/dcs-srs/Presets:/opt/srs/Presets"

    environment:
      # ===== GENERAL RADIO SETTINGS =====

      # Log all radio transmissions to file (true/false)
      TRANSMISSION_LOG_ENABLED: "false"

      # Export connected clients list to JSON file (true/false)
      CLIENT_EXPORT_ENABLED: "false"

      # Enable server-side channel presets (true/false)
      SERVER_SIDE_PRESETS_ENABLED: "false"

      # Enable HTTP server for SRS management endpoints (true/false)
      HTTP_SERVER_ENABLED: "true"

      # Port for the HTTP server (must match exposed port above, e.g., 8080:8080)
      HTTP_SERVER_PORT: "8080"

      # ===== ADVANCED RADIO SETTINGS =====

      # Export data for LotATC (Situational Awareness tool) (true/false)
      LOTATC_EXPORT_ENABLED: "false"

      # Frequencies that are always available for testing (comma-separated MHz)
      TEST_FREQUENCIES: "247.2,120.3"

      # Frequencies available in the lobby before joining a mission (comma-separated MHz)
      GLOBAL_LOBBY_FREQUENCIES: "248.22"

      # Enable External AWACS mode for server-side radio management (true/false)
      EXTERNAL_AWACS_MODE: "true"

      # Prevent enemy teams from hearing each other's radio (true/false)
      COALITION_AUDIO_SECURITY: "false"

      # Prevent spectators from hearing any radio communications (true/false)
      SPECTATORS_AUDIO_DISABLED: "false"

      # Enable Line of Sight radio limitations (true/false)
      LOS_ENABLED: "false"

      # Enable distance-based radio range limitations (true/false)
      DISTANCE_ENABLED: "false"

      # Enable real-world radio transmission effects (true/false)
      IRL_RADIO_TX: "false"

      # Enable real-world radio interference effects (true/false)
      IRL_RADIO_RX_INTERFERENCE: "false"

      # Allow more than 10 radio presets per aircraft (true/false)
      RADIO_EXPANSION: "true"

      # Allow encrypted radio communications (true/false)
      ALLOW_RADIO_ENCRYPTION: "true"

      # Force all radios to use encryption (true/false)
      STRICT_RADIO_ENCRYPTION: "false"

      # Show number of users tuned to each frequency (true/false)
      SHOW_TUNED_COUNT: "true"

      # Override individual radio effects settings (true/false)
      RADIO_EFFECT_OVERRIDE: "false"

      # Show the name of who is transmitting (true/false)
      SHOW_TRANSMITTER_NAME: "true"

      # Number of days to keep transmission logs (number)
      TRANSMISSION_LOG_RETENTION: "2"

      # Maximum number of retransmission nodes (0 = unlimited)
      RETRANSMISSION_NODE_LIMIT: "0"

      # ===== SERVER CONNECTION SETTINGS =====

      # File path for exporting connected clients list
      CLIENT_EXPORT_FILE_PATH: "clients-list.json"

      # IP address the server listens on (0.0.0.0 = all interfaces)
      SERVER_IP: "0.0.0.0"

      # Port number the server listens on
      SERVER_PORT: "5002"

      # Automatically configure router port forwarding via UPnP (true/false)
      UPNP_ENABLED: "true"

      # Check for beta version updates (true/false)
      CHECK_FOR_BETA_UPDATES: "false"

      # ===== EXTERNAL AWACS MODE PASSWORDS =====

      # Password for blue team external control
      EXTERNAL_AWACS_MODE_BLUE_PASSWORD: "blue"

      # Password for red team external control
      EXTERNAL_AWACS_MODE_RED_PASSWORD: "red"
