name: Build and Push to GHCR

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry (GHCR)
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        IMAGE_NAME=ghcr.io/jayc-adi/dcs-srs-server:2.2.0.1-beta-r1
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME